### Obtener productos
GET http://127.0.0.1:8000/api/productos
Accept: application/json
Authorization: Bearer 3|f6oSyiY53VsWcOo8QJvsvTLsiwki6mOuOPpfKlAp

### Obtener un producto
GET http://127.0.0.1:8000/api/productos/3
Accept: application/json
Authorization: Bearer 2|LG5cKX019hQ1uEy70fNyUcToB5twSRbatpEjSB3K

### Crear un producto
POST http://127.0.0.1:8000/api/productos
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|LG5cKX019hQ1uEy70fNyUcToB5twSRbatpEjSB3K

{
    "categoria_id":2
    , "subcategoria_id":3
    , "unidad_medida_id":3
    , "producto":"Producto creado a través de API"
    , "costo_unitario":15
    , "precio_unitario":22
    , "existencias":1000
    , "descripcion":"Producto nuevo creado a través de llamada a API"
    , "estatus":"activo"
}

### Editar un producto
PUT http://127.0.0.1:8000/api/productos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|Gv9rvjOaDCj7L2oi8xRiJCosWOV12a4ak95QRhUi

{
    "categoria_id":2
    , "producto":"Producto modificado a través de API"
    , "costo_unitario":15.5
    , "precio_unitario":22.5
    , "existencias":1000.5
    , "descripcion":"Producto nuevo modificado a través de llamada a API"
    , "estatus":"inactivo"
}